### ISSUE TITLE
Parsec Switcher v1 Roadmap

### ISSUE THREAD

**Issue by adsau59** [DefineX-Studios/parsec-account-switcher#1]
# We are feature locking this version now, please add new ideas in [this issue](https://github.com/DefineX-Studios/parsec-account-switcher/issues/50) unless they are critical for this version

Tech
- [x] create project
- [x] #2
- [x] backup token function
- [x] restore token function

CLI
- [x] cli command to backup a token, then restore the account needed to used
- [x] cli to create new account
- [x] Cli for setup

GUI
- [x] #15
- [x] Decide the tech stack
- [x] #23
- [x] refactor for cli and gui to work through same entry point
- [x] #40
- [x] review and merge PR

Shortcut
- [x] #39
- [x] #41

Enhancements
- [x] #27
- [x] create event for config changed (which can be used by gui to re render)
- [x] #25
- [x] #29
- [x] #28

Cleanup
- [x] remove tools folder (move commands inside js directly)
- [x] change license to MIT in package.json and add license in repo too
- [x] change author name to DefineX Studios

Testing
- [x] #11
- [x] #32
- [x] #53

Bugs:
- [x] #12 
- [x] #43
- [x] #44
- [x] #45
- [x] #48
- [x] #46
- [x] #49 
- [x] #52 
- [x] #54

**Comment by adsau59** [comment]
all tasks done, good job everyone, closing the issue
